<h2 align='center'>NLP Tutorial: Text Representation - Bag Of Words (BOW)</h2>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [5]:
df.shape

(5572, 3)

In [6]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

<h3>Train test split</h3>

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [8]:
X_train.shape

(4457,)

In [9]:
X_test.shape

(1115,)

In [10]:
type(X_train)

pandas.Series

In [11]:
X_train[:4]

2392                          PICK UR FONE UP NOW U DUMB?
3644    Sorry, left phone upstairs. OK, might be hecti...
2587    If you don't respond imma assume you're still ...
4140    Ever green quote ever told by Jerry in cartoon...
Name: Message, dtype: str

In [12]:
type(y_train)

pandas.Series

In [13]:
y_train[:4]

2392    0
3644    0
2587    0
4140    0
Name: spam, dtype: int64

In [14]:
type(X_train.values)

pandas.arrays.StringArray

<h3>Create bag of words representation using CountVectorizer</h3>

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59585 stored elements and shape (4457, 7738)>

In [16]:
# To convert it to an array
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7738,))

In [17]:
X_train_cv.shape

(4457, 7738)

In [28]:
# To see entire vocabulary
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'zyada', 'èn', '〨ud'],
      shape=(7738,), dtype=object)

In [29]:
#each word in vocabulary with its index position
v.vocabulary_

{'pick': 5204,
 'ur': 7197,
 'fone': 2913,
 'up': 7181,
 'now': 4844,
 'dumb': 2479,
 'sorry': 6335,
 'left': 4064,
 'phone': 5190,
 'upstairs': 7195,
 'ok': 4918,
 'might': 4473,
 'be': 1274,
 'hectic': 3385,
 'but': 1575,
 'would': 7607,
 'all': 907,
 'my': 4665,
 'birds': 1369,
 'with': 7546,
 'one': 4940,
 'fell': 2797,
 'swoop': 6657,
 'it': 3752,
 'date': 2166,
 'if': 3595,
 'you': 7702,
 'don': 2404,
 'respond': 5734,
 'imma': 3618,
 'assume': 1110,
 're': 5580,
 'still': 6482,
 'asleep': 1102,
 'and': 953,
 'start': 6446,
 'calling': 1618,
 'shit': 6094,
 'ever': 2654,
 'green': 3235,
 'quote': 5531,
 'told': 6941,
 'by': 1590,
 'jerry': 3812,
 'in': 3634,
 'cartoon': 1671,
 'person': 5166,
 'who': 7491,
 'irritates': 3738,
 'always': 927,
 'is': 3742,
 'the': 6806,
 'loves': 4233,
 'vry': 7326,
 'much': 4633,
 'fails': 2741,
 'to': 6924,
 'express': 2717,
 'gud': 3262,
 'nyt': 4876,
 'carlos': 1662,
 'says': 5920,
 'he': 3364,
 'll': 4156,
 'at': 1119,
 'mu': 4631,
 'lt': 4248

In [30]:
# To see where is non zero values of a vector
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7738,))

In [31]:
np.where(X_train_np[0] != 0)

(array([2479, 2913, 4844, 5204, 7181, 7197]),)

In [36]:
X_train[:4][2392]

'PICK UR FONE UP NOW U DUMB?'

In [37]:
X_train_np[0][2479]

np.int64(1)

<h3>Train the naive bayes model</h3>

In [39]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [41]:
# transform x_test
X_test_cv = v.transform(X_test)

<h3>Evaluate Performance</h3>

In [42]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       987
           1       0.98      0.91      0.94       128

    accuracy                           0.99      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [43]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

<h3>Train the model using sklearn pipeline and reduce number of lines of code</h3>

In [44]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [45]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [46]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       987
           1       0.98      0.91      0.94       128

    accuracy                           0.99      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.99      0.99      0.99      1115

